.travis.yml

chore(tests): use 3.5.0

---

.travis.yml
CONTRIBUTING.md
README.md
integration/clean.sh
integration/start.sh
integration/stop.sh

As part of this, validated all tests passed on OS X after installing/starting a local ZooKeeper server.

Add a bit more detail to CONTRIBUTING.md

---

CHANGES.md
zk_shell/shell.py
zk_shell/tests/test_json_cmds.py

feature(json_dupes_for_key): cmd to spot znodes with a duped key

---

CHANGES.md
zk_shell/shell.py

fix(ls): always sort znodes

---

CHANGES.md
zk_shell/shell.py

feature(edit): add a command for inline editing

---

README.md
requirements.txt
setup.py

chore(deps): bump Kazoo dependency to 2.2

---

CHANGES.md
zk_shell/shell.py
zk_shell/tests/shell_test_case.py
zk_shell/tests/test_basic_cmds.py

This depends on https://github.com/python-zk/kazoo/pull/333 being merged

feature(reconfig): adds reconfig command (as offered by ZOOKEEPER-107)

---

.gitignore
.travis.yml

chore(tests): remove old integration leftovers

---

zk_shell/shell.py

refactor(shell): use BooleanOptional instead of to_bool

---

zk_shell/shell.py
zk_shell/util.py

refactor(shell): use {Float, Integer}Optional & remove to_float

---

.travis.yml

chore(travis): do not install libcppunit-dev

---

CHANGES.md
zk_shell/shell.py

feature(exists): add `pretty_date` option to exists

---

zk_shell/shell.py
zk_shell/tests/test_four_letter_cmds.py
zk_shell/util.py
zk_shell/xclient.py

feature(match): add an optional match param for 4-letter cmds

---

CHANGES.md
zk_shell/shell.py

feature(exists): print zxids as hex

---

CHANGES.md
zk_shell/shell.py
zk_shell/tests/test_basic_cmds.py

feature(shell): session_info now supports [match]

---

CHANGES.md
zk_shell/shell.py
zk_shell/tests/test_basic_cmds.py

feature(shell): new echo command to display fmt strings

---

zk_shell/shell.py

It seems nice to display the hosts in the prompt so the user knows what hosts they're connected to - e.g.:
```
$ zk-shell $DOCKER_IP:2181
Welcome to zk-shell (1.1.1)
(CONNECTING [192.168.223.128:2181]) />
(CONNECTED [192.168.223.128:2181]) />
$ zk-shell
Welcome to zk-shell (1.1.1)
(DISCONNECTED) /> connect 192.168.223.128:2181
(CONNECTING []) />
(CONNECTED [192.168.223.128:2181]) /> disconnect
(DISCONNECTED) />
```

Display hosts in prompt

---

.travis.yml
zk_shell/cli.py
zk_shell/copy_util.py
zk_shell/shell.py
zk_shell/tests/shell_test_case.py
zk_shell/tests/test_connect.py
zk_shell/tests/test_cp_cmds.py

This PR aims to fix the use of reserved keyword `async` introduced in python 3.7

Fix use of reserved async keyword introduced in python 3.7

---

zk_shell/copy_util.py

Change line back to how it was prior to the find/replace that initially broke it
fixes #102

fix copy function

---

zk_shell/shell.py
zk_shell/xclient.py

If zk_shell is used as a library this would allow to initalize a (eg. kerberos auth capable) kazoo client and pass it to zk_shell.shell. In this way such authentication schemes could be supported that the current official kazoo client is not able to support. Eg. sasl auth would be possible if someone extended kazoo.client with sasl capabilities. There is a perfectly functioning (pending) PR to kazoo which does just that (kerberos auth via sasl).

Ability to pass a kazoo client for XClient to use
